name: Data Fetch Workflow

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:         # Allows manual trigger
  push:
    branches: [ main ]      # Runs on push to main branch
    paths:
      - 'json/**'          # Only trigger when json files change

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install axios

      - name: Fetch data
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          API_USERNAME: ${{ secrets.API_USERNAME }}
          API_PASSWORD: ${{ secrets.API_PASSWORD }}
        run: node .github/scripts/fetch-data.js

      - name: Commit and push changes
        if: success()
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add json/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update data files - $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
            git push
          fi
